name = "nuxt-esa"
entry = "./.output/server/index.mjs"
installCommand = "npm install"
buildCommand = "npm run build -- --preset=./preset"

[dev]
port = 18_080
localUpstream = ""

[assets]
directory = "./.output/public"
notFoundStrategy = "404Page"
